#!/usr/bin/env bash

LARAVEL_PATH=${LARAVEL_PATH:-/var/www/laravel}
VERSION="$(cat VERSION)"

source /usr/local/bin/lib/lib.sh

function setup_env() {

    APP_VERSION=${VERSION:-0.0.1}
    echo APP_VERSION=${APP_VERSION} > ${LARAVEL_PATH}/.env.ext

    APP_ENV=${APP_ENV:-production}
    echo APP_ENV=${APP_ENV} >> ${LARAVEL_PATH}/.env.ext

    APP_KEY=${APP_KEY:-"base64:X+lyMi0nK+zHpCuB4eBLIjbQqsWTTC5mNxoevPZw8BA="}
    echo APP_KEY=${APP_KEY} >> ${LARAVEL_PATH}/.env.ext

    APP_DEBUG=${APP_DEBUG:-false}
    echo APP_DEBUG=${APP_DEBUG} >> ${LARAVEL_PATH}/.env.ext

    SELECTEL_API_TOKEN=${SELECTEL_API_TOKEN}
    echo SELECTEL_API_TOKEN=${SELECTEL_API_TOKEN} >> ${LARAVEL_PATH}/.env.ext

    SELECTEL_API_URL=${SELECTEL_API_URL}
    echo SELECTEL_API_URL=${SELECTEL_API_URL} >> ${LARAVEL_PATH}/.env.ext

    cat ${LARAVEL_PATH}/.env.ext

    mo -s=${LARAVEL_PATH}/.env.ext -u ${LARAVEL_PATH}/.env.template > ${LARAVEL_PATH}/.env
    rm ${LARAVEL_PATH}/.env.ext

    echo 'setup env complete'
    echo '======= .env ======='
}

set -e

cd ${LARAVEL_PATH}
echo "" > storage/logs/laravel.log

echo '<<< api setup envs'
setup_env

# echo '<<< generate key'
# php artisan key:generate

# echo '<<< set maintenance'
# php artisan down

# echo '<<< migrate'
# php artisan migrate --force || throw

echo '<<< update vendors & package'
php artisan package:discover || throw

# echo '<<< set off maintenance'
# php artisan up

echo '<<< config cache'
php artisan config:cache || throw
php artisan view:cache || throw
# php artisan route:cache
php artisan event:cache || throw


echo '<<< run http'
exec apache2-foreground
